### ISSUE TITLE
Apply lazyloading

### ISSUE THREAD

**Issue by alesanca** [Pedrobusou/ygocm#11]
Attemp to lazy-load the cards in order to lower the load put on the client when printing a high number of search results. This can sometimes freeze user's browser.

**Comment by Pedrobusou** [comment]
In the end it seemed that printing all cards at once was not a big problem, as images far away from the viewport are not displayed until the user scroll to them.

I have added:

- initial search of cards
- default sort by newest
- when img fails loading from googleapi, load it from ygoprodeck
