### ISSUE TITLE
NavMenu: highlight active page

### ISSUE THREAD

**Issue by Pedrobusou** [Pedrobusou/ygocm#12]
Would be nice to highlight the current page on the menu.
Should be a different effect than the one performed on hover,

For that, we probably need to create a new useState, to keep track on which is the current page. This state has to be updated whenever the user changes the page, either by using the menu, or by writting another url.

Maybe we can use the pages array (used at NavMenu component), rising it up few layers.

**Comment by alesanca** [comment]
https://reacttraining.com/react-router/web/api/Link
